title: My Blog
description: A simple blog on GitHub Pages
markdown: kramdown

# Use Minima, which is still the default blog-friendly theme
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

minima:
  skin: dark
